### PR TITLE
infra: Add kcli scripts to start OCP with the ignition and MCO here.

### PR DESCRIPTION
**Pull request by qinqon**
Depends on: 
- https://github.com/RHsyseng/rhcos-slb/pull/44

### CODE REVIEW

**Review by phoracek — CHANGES_REQUESTED** [review]
Please don't mix kcli, NNCP and MCO changes.

**Comment by qinqon** [comment]
> Please don't mix kcli, NNCP and MCO changes.

The idea is to synthesize what is needed for kcli from original ones, what is here is not going to be merged

**Comment by phoracek** [comment]
Oh, understood, thanks!

**Comment by qinqon** [comment]
After the NNCP is applied on masters the cluster apiserver IP `192.168.122.253` sometimes is lost or sometimes it goes back to the primary nic instead of pointing to the ovs interface so api connectivity is lost, when applied at workers this is no issue since the primary nic there is not for apiserver purposes.

**Comment by qinqon** [comment]
The only pointer I find to set the "descriptin" field at command line is using python, https://github.com/freedesktop/NetworkManager/blob/master/examples/python/gi/setting-user-data.py.

**Comment by qinqon** [comment]
There is some issue with the init-interfaces.sh the secondary network is not correctly associated to the device

```
[core@goldman-master-0 ~]$ nmcli c show 
NAME                            UUID                                  TYPE      DEVICE          
enx525400f68001                 94d2b5d9-0588-43d0-932b-e2ce06dd276b  ethernet  enx525400f68001 
ethernet-enx525400f68002-31529  20585e65-b813-449f-8fce-0a1d054d0bac  ethernet  --              
```

**Comment by qinqon** [comment]
There is a bug at nmpolicy that prevent using `description` field https://github.com/nmstate/nmpolicy/issues/74.

**Pull request closed without merging**
