### PR TITLE
[simplify-networking] init-interfaces: Search nm connection by mac

### PR DESCRIPTION
**Pull request by qinqon**
The most well know information is the MAC address, this change use it to
find the NetworkManager connection at hand.

The kcli tests are fine:

```bash
$ kubectl get nns rhocs-slb-master-0.redhat.com -o json | jq '.status.currentState.interfaces[]  | select(.["mac-address"]=="52:54:00:F6:80:01").name'
"enx525400f68001"

$kubectl get nns rhocs-slb-master-0.redhat.com -o json | jq '.status.currentState.interfaces[]  | select(.["mac-address"]=="52:54:00:F6:80:02").name'
"enx525400f68002"

$ kubectl get nns rhocs-slb-worker-0.redhat.com -o json | jq '.status.currentState.interfaces[]  | select(.["mac-address"]=="52:54:00:F6:80:03").name'
"enx525400f68003"

$ kubectl get nns rhocs-slb-worker-0.redhat.com -o json | jq '.status.currentState.interfaces[]  | select(.["mac-address"]=="52:54:00:F6:80:04").name'
"enx525400f68004"
```

```bash
$ ./kcli/add-slb.sh 
+ oc apply -f add-slb-nncp.yaml
nodenetworkconfigurationpolicy.nmstate.io/slb created
+ ./kcli/update-keepalived.sh brcnv-iface
+ interface=brcnv-iface
+ kcli ssh rhocs-slb-master-0 -- 'sudo sed -i '\''s@interface .*@interface brcnv-iface@'\'' /etc/kubernetes/keepalived.conf'
++ kcli ssh rhocs-slb-master-0 -- 'sudo crictl pods --namespace openshift-infra --name keepalived-rhocs-slb-master-0.redhat.com --output json |jq -r .items[0].id'
+ pod_id=5121166d1e8c2d36613d537683560014d52ea1d063e18927aacb51c0e27e5c91
+ kcli ssh rhocs-slb-master-0 -- 'sudo crictl rmp --force 5121166d1e8c2d36613d537683560014d52ea1d063e18927aacb51c0e27e5c91'
Stopped sandbox 5121166d1e8c2d36613d537683560014d52ea1d063e18927aacb51c0e27e5c91
Removed sandbox 5121166d1e8c2d36613d537683560014d52ea1d063e18927aacb51c0e27e5c91
+ ./kcli/retry.sh oc wait nncp slb --for=condition=Available
+ n=0
+ '[' 0 -ge 5 ']'
+ oc wait nncp slb --for=condition=Available
Unable to connect to the server: dial tcp 192.168.122.253:6443: i/o timeout
+ n=1
+ '[' 1 -ge 5 ']'
+ oc wait nncp slb --for=condition=Available
nodenetworkconfigurationpolicy.nmstate.io/slb condition met
+ break
```

### CODE REVIEW

**Comment by qinqon** [comment]
@RamLavi  @dcritch @phoracek

**Comment by dcritch** [comment]
Hi @qinqon 

I think we still need the `interface-name` check in there as well. On a clean install, we need MACs, but on an update one, we need the `interface-name`. I also think we need a check to see if devices have already been initialised. I'm seeing duplicate interfaces even with the latest changes.

Here's what I've come up with after today:
~~~
#!/usr/bin/env bash

set -ex

is_configured() {

  if [[ $(grep primary /etc/NetworkManager/system-connections/* | wc -l) -eq 1 && $(grep secondary /etc/NetworkManager/system-connections/* | wc -l) -eq 1 ]]; then
    echo "interfaces already configured"
    exit 0
  fi
  
}

is_con_exists() {
  local con_name=$1
  if nmcli -t -g NAME con show | grep -w -q "$con_name"; then
    return 0 # true
  fi
  return 1 # false
}

is_con_active() {
  local con_name=$1
  if nmcli -t -g NAME con show --active | grep -w -q "$con_name"; then
    return 0 # true
  fi
  return 1 # false
}

get_con_name_by_device() {
  local dev_name=$1
  local mac=$(echo $2 | sed -e 's/\\\|://g')
  while read -r con; do
    if [[ "$(nmcli -g 802-3-ethernet.mac-address c show "${con}" | tr '[A-Z]' '[a-z]' | sed -e 's/\\\|://g')" == "$mac" || $(nmcli -g connection.interface-name c show "${con}") == "${dev_name}" ]]; then
      echo "${con}"
      break
    fi
  done <<< "$(nmcli -g NAME c show)"
}

generate_new_con_name() {
  local device_name=$1
  #printf "ethernet-%s-%s" "$device_name" "$RANDOM"
  printf "ethernet-%s-%s" "$device_name" "$RANDOM"
}

set_description() {
  local mac=$1
  local nic=$2
  local description=$3
  local cons=$(egrep -l -i "mac-address=$mac|interface-name=$nic" /etc/NetworkManager/system-connections/*)
  for c in $cons; do
      if ! grep nmstate.interface.description $c; then
         echo "" >> $c
         echo "[user]" >> $c
         echo nmstate.interface.description=$description >> $c
      else
         sed -i "s/nmstate\.interface\.description=.*/nmstate.interface.description=$description/" $c
      fi
done
}

if [[ ! -f /boot/mac_addresses ]] ; then
  echo "no mac address configuration file found .. exiting"
  exit 1
fi

is_configured

primary_mac="$(awk -F= '/PRIMARY_MAC/ {print $2}' < /boot/mac_addresses | tr '[:upper:]' '[:lower:]')"
secondary_mac="$(awk -F= '/SECONDARY_MAC/ {print $2}' < /boot/mac_addresses | tr '[:upper:]' '[:lower:]')"

default_device=""
secondary_device=""
default_connection_name=""
secondary_connection_name=""

for dev in $(nmcli device status | awk '/ethernet/ {print $1}'); do
  dev_mac=$(nmcli -g GENERAL.HWADDR dev show "$dev" | sed -e 's/\\//g' | tr '[:upper:]' '[:lower:]')
  case $dev_mac in
    $primary_mac)
      default_device="$dev"
      default_connection_name=$(get_con_name_by_device "$dev" "$primary_mac")
      ;;
    $secondary_mac)
      secondary_device="$dev"
      secondary_connection_name=$(get_con_name_by_device "$dev" "$secondary_mac")
      ;;
    *)
      ;;
   esac
done

echo -e "default dev: $default_device (CONNECTION.NAME $default_connection_name)\nsecondary dev: $secondary_device (CONNECTION.NAME $secondary_connection_name)"
if [[ -z "$default_device" ]] || [[ -z "$secondary_device" ]]; then
  echo "error: primary/secondary device name not found"
  exit 1
fi

if eval ! is_con_exists "\"$default_connection_name\""; then
  default_connection_name="$(generate_new_con_name "$default_device")" && export default_connection_name
  nmcli con add type ethernet \
                conn.interface "$default_device" \
                connection.autoconnect yes \
                ipv4.method auto \
                con-name "$default_connection_name" \
                802-3-ethernet.mac-address $primary_mac
fi
if eval ! is_con_active "\"$default_connection_name\""; then
  nmcli con up "$default_connection_name"
fi

if eval ! is_con_exists "\"$secondary_connection_name\""; then
  secondary_connection_name="$(generate_new_con_name "$secondary_device")" && export secondary_connection_name
  nmcli con add type ethernet \
                conn.interface "$secondary_device" \
                connection.autoconnect yes \
                ipv4.method disabled \
                ipv6.method disabled \
                con-name "$secondary_connection_name" 
                #802-3-ethernet.mac-address $secondary_mac
fi
if eval ! is_con_active "\"$secondary_connection_name\""; then
  nmcli con up "$secondary_connection_name"
fi

set_description "$primary_mac" "$default_device" primary
set_description "$secondary_mac" "$secondary_device" secondary

nmcli c reload
~~~

Something is still messed up though. After multiple reboots, I do not get duplicate interfaces, but as soon as I apply the nncp and reboot, they start to show up:
~~~
[davidc@optimo gsci]$ for node in $(oc get nodes | grep worker | awk '{print $1}'); do echo $node; ssh -q core@$node nmcli con; done
worker-0.gsci.cloud.lab.eng.bos.redhat.com
NAME              UUID                                  TYPE           DEVICE          
brcnv-iface       e13998e2-ab3c-47e9-b5c6-d53c1fe2e844  ovs-interface  brcnv-iface     
bond0-port        2790a893-1777-4db9-8f7d-a0ab5d1d0b74  ovs-port       bond0           
brcnv             ee8759f2-daf4-4e96-bf66-40e7932977e2  ovs-bridge     brcnv           
brcnv-iface       8e2ace7b-f055-4fc4-b305-1e51fa5f5dd0  ovs-port       brcnv-iface     
enx1c4024995c56   b01752d5-1636-49fe-ba50-2177abe660d9  ethernet       enx1c4024995c56 
enx1c4024995c58   d685df91-933e-4059-8a28-e852f6d6ba0d  ethernet       enx1c4024995c58 
Wired Connection  db17bb10-f08f-4871-b8e3-c9bb35dce0ed  ethernet       --              
worker-1.gsci.cloud.lab.eng.bos.redhat.com
NAME              UUID                                  TYPE           DEVICE          
Wired Connection  2ce1db5d-6306-4070-b653-4f6c21e9bddd  ethernet       enx1c4024995c63 
brcnv-iface       c1e2e858-4cf8-4948-a595-d8ac5f5cbfb6  ovs-interface  brcnv-iface     
bond0-port        87cf2e74-25b5-475e-a538-4c13c27dfe25  ovs-port       bond0           
brcnv             f637a842-2f75-4223-b738-85a4a57feb98  ovs-bridge     brcnv           
brcnv-iface       4a1981f4-6bb1-4c14-ba0f-a7333e21877d  ovs-port       brcnv-iface     
enx1c4024995c63   7b8a699a-3d27-444d-8f8f-ee17a48e38fc  ethernet       enx1c4024995c63 
enx1c4024995c65   b1e3462b-049c-46bd-abbf-6c1ea35c0f0e  ethernet       enx1c4024995c65 
worker-2.gsci.cloud.lab.eng.bos.redhat.com
NAME              UUID                                  TYPE           DEVICE          
brcnv-iface-if    6cf78109-f5d5-45b5-a66d-4a7f0e3b5381  ovs-interface  brcnv-iface     
bond0-port        d17339bb-2233-42c3-8b43-bccaca218a84  ovs-port       bond0           
brcnv-br          8af8540b-fa68-4e84-81ec-1e30ee4a051f  ovs-bridge     brcnv           
brcnv-iface-port  9272988b-dc69-442f-a041-d8f286cc20a4  ovs-port       brcnv-iface     
enx1c4024995c70   6f05e93d-bc3c-418b-ba47-63ea29a762eb  ethernet       enx1c4024995c70 
enx1c4024995c72   b168efcd-c4a7-4245-92c1-536b5e3c3fc5  ethernet       enx1c4024995c72 
Wired Connection  5b4ccb5f-d94c-480d-8044-db13d61a455a  ethernet       --              
[davidc@optimo gsci]$ for node in $(oc get nodes | grep worker | awk '{print $1}'); do echo $node; ssh -q core@$node 'sudo egrep "primary|secondary" /etc/NetworkManager/system-connections/*'; done
worker-0.gsci.cloud.lab.eng.bos.redhat.com
/etc/NetworkManager/system-connections/brcnv-iface-if.nmconnection:nmstate.interface.description=primary
/etc/NetworkManager/system-connections/default_connection.nmconnection:nmstate.interface.description=primary
/etc/NetworkManager/system-connections/enx1c4024995c56-b01752d5-1636-49fe-ba50-2177abe660d9.nmconnection:nmstate.interface.description=primary
/etc/NetworkManager/system-connections/ethernet-enx1c4024995c58-12334.nmconnection:nmstate.interface.description=secondary
worker-1.gsci.cloud.lab.eng.bos.redhat.com
/etc/NetworkManager/system-connections/default_connection.nmconnection:nmstate.interface.description=primary
/etc/NetworkManager/system-connections/enx1c4024995c63.nmconnection:nmstate.interface.description=primary
/etc/NetworkManager/system-connections/ethernet-enx1c4024995c65-25898.nmconnection:nmstate.interface.description=secondary
worker-2.gsci.cloud.lab.eng.bos.redhat.com
/etc/NetworkManager/system-connections/brcnv-iface-if.nmconnection:nmstate.interface.description=primary
/etc/NetworkManager/system-connections/default_connection.nmconnection:nmstate.interface.description=primary
/etc/NetworkManager/system-connections/enx1c4024995c70.nmconnection:nmstate.interface.description=primary
/etc/NetworkManager/system-connections/ethernet-enx1c4024995c72-18739.nmconnection:nmstate.interface.description=secondary
~~~

ovs looks fine though. The additional devices tagged as primary might be noise and not something we need to worry about?
~~~
$ for node in $(oc get nodes | grep worker | awk '{print $1}'); do echo $node; ssh -q core@$node sudo ovs-vsctl show | grep -A8 'Bridge brcnv'; done
worker-0.gsci.cloud.lab.eng.bos.redhat.com
    Bridge brcnv
        Port brcnv-iface
            Interface brcnv-iface
                type: internal
        Port bond0
            Interface enx1c4024995c58
                type: system
            Interface enx1c4024995c56
                type: system
worker-1.gsci.cloud.lab.eng.bos.redhat.com
    Bridge brcnv
        Port bond0
            Interface enx1c4024995c65
                type: system
            Interface enx1c4024995c63
                type: system
        Port brcnv-iface
            Interface brcnv-iface
                type: internal
worker-2.gsci.cloud.lab.eng.bos.redhat.com
    Bridge brcnv
        Port bond0
            Interface enx1c4024995c70
                type: system
            Interface enx1c4024995c72
                type: system
        Port brcnv-iface
            Interface brcnv-iface
                type: internal
~~~

**Comment by dcritch** [comment]
I'm testing again, but with L7 being a `-ge` rather than `-eq` since its probably expected that `brcnv` would also get the MAC `interface-name` set.

I think we're getting close! I'm aiming to test upgrades over the next day or so. We still might have to do some cleanup of the old interfaces, or make sure the ones w/ nncp match what was created with the `setup-ovs` script.

**Comment by qinqon** [comment]
Can you open a PR with proper fix? I will close this one.

**Comment by phoracek** [comment]
That's one way of doing it! :D

**Comment by qinqon** [comment]
> Shoot. I thought I was pushing to my fork, and I didn't know I was even able to push to this repo... but oops :/ I just pushed the latest to the simplfy-networking branch by mistake

hehe no problem, I will close this PR and test this branch with kcli.

**Comment by phoracek** [comment]
Let's leave it there and open a follow-up if we find any issues with https://github.com/RHsyseng/rhcos-slb/commit/ef360ae6d1fc11562c074a1c270766edfe7f5fe1

**Pull request closed without merging**
